"""auto-vote

Revision ID: 357d6f7c5a67
Revises: 2bf8f0cb988f
Create Date: 2021-11-10 07:58:46.623239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357d6f7c5a67'
down_revision = '2bf8f0cb988f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes', 
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post_id'], ondelete='CASCADEe'),
    sa.ForeignKeyConstraint(['user_id'], ['user_id'], ondelete='CASCADEe'),
    sa.ForeignKeyConstraint('user_id', 'post_id')
    )       
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
